// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.'
    }
  ],
  devSidebar: [
    {
      type: 'autogenerated',
      dirName: '.'
    }
  ],
  contractsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.'
    }
  ]
};

module.exports = sidebars;
